WITH CTE AS (
    SELECT 
        BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
, CTE2 AS (
    SELECT f.BOARD_ID, CONCAT(f.FILE_ID, f.FILE_NAME,f.FILE_EXT) as d, f.FILE_ID
    FROM USED_GOODS_FILE f JOIN CTE c
        ON f.BOARD_ID = c.BOARD_ID
)
SELECT CONCAT_WS('/', '/home/grep/src',BOARD_ID,d) AS FILE_PATH
FROM CTE2
ORDER BY FILE_ID DESC