WITH CTE1 AS (
    SELECT c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR c JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        ON c.CAR_ID = h.CAR_ID and c.CAR_TYPE in ('세단','SUV')
    GROUP BY c.CAR_ID
    HAVING MAX(h.END_DATE) <'2022-11-01'
),
CTE2 AS (
    SELECT c.CAR_ID, c.CAR_TYPE, ROUND((c.DAILY_FEE * 30)*((100-p.DISCOUNT_RATE)/100),0) AS FEE
    FROM CTE1 c JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
        ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE ='30일 이상'
)
SELECT *
FROM CTE2
WHERE FEE BETWEEN 500000 AND 1999999
ORDER BY 3 DESC, 2, 1 DESC