WITH CTE AS (
    SELECT CAR_ID,
        CASE 
        WHEN '2022-10-16' not BETWEEN START_DATE AND END_DATE THEN '0'
        ELSE '1' END AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
), CTE2 AS (
    SELECT CAR_ID,
        CASE WHEN SUM(AVAILABILITY) OVER (PARTITION BY CAR_ID ORDER BY CAR_ID) = 1 THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY
    FROM CTE
)
SELECT *
FROM CTE2
GROUP BY CAR_ID
ORDER BY CAR_ID DESC