WITH OVER_THREE AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID)>2
)
SELECT u.USER_ID
    ,u.NICKNAME
    ,CONCAT(u.CITY,' ',u.STREET_ADDRESS1,' ',u.STREET_ADDRESS2) AS 전체주소
    ,CONCAT(SUBSTR(u.TLNO, 1, 3),"-",SUBSTR(u.TLNO, 4, 4),"-",SUBSTR(u.TLNO, 8, 4)) "전화번호"
FROM USED_GOODS_USER u JOIN OVER_THREE t
    ON u.USER_ID = t.WRITER_ID
ORDER BY 1 DESC