WITH CTE AS (
    SELECT 
        CAR_ID
        , ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY car_id
)
SELECT CAR_ID, AVERAGE_DURATION
FROM CTE
WHERE AVERAGE_DURATION >=7
ORDER BY 2 DESC, 1 DESC