WITH CTE AS (
    SELECT DISTINCT(i.USER_ID), i.GENDER, YEAR(s.SALES_DATE) as YEAR, MONTH(s.SALES_DATE) as MONTH
    FROM USER_INFO i JOIN ONLINE_SALE s
        ON i.USER_ID = s.USER_ID AND i.GENDER IS NOT NULL AND s.SALES_AMOUNT >0
)
SELECT YEAR,MONTH, GENDER,
    COUNT(USER_ID) as USERS

FROM CTE
GROUP BY YEAR,MONTH,GENDER
ORDER BY YEAR,MONTH,GENDER