WITH CTE AS (
    SELECT 
        FOOD_TYPE,REST_ID, REST_NAME,FAVORITES,
        RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) as rk
    FROM REST_INFO
    )
SELECT FOOD_TYPE,REST_ID, REST_NAME, FAVORITES
FROM CTE
WHERE rk = 1
ORDER BY FOOD_TYPE DESC
