WITH CTE AS (
SELECT e1.id AS ID, CASE WHEN e2.parent_id IS NULL THEN 0 ELSE 1 END AS p
FROM ECOLI_DATA e1 left JOIN ECOLI_DATA e2
    ON e1.ID = e2.parent_id
)
SELECT ID, SUM(p) AS CHILD_COUNT
FROM CTE
GROUP BY ID

