
SELECT o.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT) * p.PRICE AS TOTAL_SALES
FROM FOOD_ORDER o JOIN FOOD_PRODUCT p
    ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE MONTH(o.PRODUCE_DATE) = 5
GROUP BY o.PRODUCT_ID
ORDER BY (SUM(o.AMOUNT) * p.PRICE) DESC, o.PRODUCT_ID
