WITH JULY_SUM AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS T_ORDER
    FROM JULY
    GROUP BY FLAVOR
), CTE AS (
    SELECT j.FLAVOR, (j.T_ORDER + f.TOTAL_ORDER) as tt
    FROM JULY_SUM j JOIN FIRST_HALF f
        ON j.FLAVOR = f.FLAVOR 
)
SELECT FLAVOR
FROM CTE
ORDER BY tt DESC
LIMIT 3
