WITH CTE AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
)
SELECT DISTINCT(c.CAR_ID)
FROM CTE c JOIN CAR_RENTAL_COMPANY_CAR r
    ON c.CAR_ID = r.CAR_ID AND r.CAR_TYPE = '세단'
ORDER BY 1 DESC