WITH CTE AS (
    SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS p_rk
    FROM ECOLI_DATA
)
SELECT ID,
    CASE
        WHEN p_rk <= 0.25 THEN 'CRITICAL'
        WHEN p_rk <= 0.5 THEN 'HIGH'
        WHEN p_rk <= 0.75 THEN 'MEDIUM'
        WHEN p_rk <= 1 THEN 'LOW'
    END AS COLONY_NAME
FROM CTE
ORDER BY ID;
