WITH RECURSIVE CTE AS (
    -- PARENTID가 NULL이면 1세대 -> 초기값 설정
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS null
    
    UNION ALL
    
    SELECT
        e.ID
        ,e.PARENT_ID
        ,(GENERATION + 1) AS GENERATION
    FROM ECOLI_DATA e
        JOIN CTE c ON e.PARENT_ID = c.ID
)
, CTE2 AS (
    SELECT c.ID, c.PARENT_ID,c.GENERATION,e.ID as id2
    FROM CTE c LEFT JOIN CTE e ON c.ID = e.PARENT_ID
    WHERE e.ID IS NULL
    
)
SELECT
    COUNT(*) AS COUNT
    ,GENERATION
FROM CTE2
GROUP BY GENERATION