WITH CTE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO

)
SELECT c.SCORE, c.EMP_NO, h.EMP_NAME, h.POSITION, h.EMAIL
FROM CTE c JOIN HR_EMPLOYEES as h
    ON c.EMP_NO = h.EMP_NO
ORDER BY c.SCORE DESC
LIMIT 1 